//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;

public abstract class Message : IMessageSerialize
{
    // 消息ID;
    private int _msgId;

    public int MsgId
    {
        get
        {
            return _msgId;
        }

        set
        {
            _msgId = value;
        }
    }
	
	public abstract void Serialize(Stream stream);
	public abstract void Deserialize(Stream stream);
}

