// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.zyyApp.Netty.ServerTest.Message.protocol;

public final class Login {
  private Login() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface pingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ping)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code ping}
   */
  public  static final class ping extends
      com.google.protobuf.GeneratedMessageLite<
          ping, ping.Builder> implements
      // @@protoc_insertion_point(message_implements:ping)
      pingOrBuilder {
    private ping() {
    }
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSerializedSize = size;
      return size;
    }

    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code ping}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping, Builder> implements
        // @@protoc_insertion_point(builder_implements:ping)
        com.zyyApp.Netty.ServerTest.Message.protocol.Login.pingOrBuilder {
      // Construct using com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:ping)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping other = (com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping) arg1;
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:ping)
    private static final com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ping();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.ping getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ping> PARSER;

    public static com.google.protobuf.Parser<ping> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface reqloginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:reqlogin)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string playerName = 1;</code>
     */
    java.lang.String getPlayerName();
    /**
     * <code>optional string playerName = 1;</code>
     */
    com.google.protobuf.ByteString
        getPlayerNameBytes();
  }
  /**
   * Protobuf type {@code reqlogin}
   */
  public  static final class reqlogin extends
      com.google.protobuf.GeneratedMessageLite<
          reqlogin, reqlogin.Builder> implements
      // @@protoc_insertion_point(message_implements:reqlogin)
      reqloginOrBuilder {
    private reqlogin() {
      playerName_ = "";
    }
    public static final int PLAYERNAME_FIELD_NUMBER = 1;
    private java.lang.String playerName_;
    /**
     * <code>optional string playerName = 1;</code>
     */
    public java.lang.String getPlayerName() {
      return playerName_;
    }
    /**
     * <code>optional string playerName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(playerName_);
    }
    /**
     * <code>optional string playerName = 1;</code>
     */
    private void setPlayerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      playerName_ = value;
    }
    /**
     * <code>optional string playerName = 1;</code>
     */
    private void clearPlayerName() {
      
      playerName_ = getDefaultInstance().getPlayerName();
    }
    /**
     * <code>optional string playerName = 1;</code>
     */
    private void setPlayerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      playerName_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!playerName_.isEmpty()) {
        output.writeString(1, getPlayerName());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!playerName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getPlayerName());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code reqlogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin, Builder> implements
        // @@protoc_insertion_point(builder_implements:reqlogin)
        com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqloginOrBuilder {
      // Construct using com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional string playerName = 1;</code>
       */
      public java.lang.String getPlayerName() {
        return instance.getPlayerName();
      }
      /**
       * <code>optional string playerName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPlayerNameBytes() {
        return instance.getPlayerNameBytes();
      }
      /**
       * <code>optional string playerName = 1;</code>
       */
      public Builder setPlayerName(
          java.lang.String value) {
        copyOnWrite();
        instance.setPlayerName(value);
        return this;
      }
      /**
       * <code>optional string playerName = 1;</code>
       */
      public Builder clearPlayerName() {
        copyOnWrite();
        instance.clearPlayerName();
        return this;
      }
      /**
       * <code>optional string playerName = 1;</code>
       */
      public Builder setPlayerNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPlayerNameBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:reqlogin)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin other = (com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin) arg1;
          playerName_ = visitor.visitString(!playerName_.isEmpty(), playerName_,
              !other.playerName_.isEmpty(), other.playerName_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  playerName_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:reqlogin)
    private static final com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new reqlogin();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqlogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<reqlogin> PARSER;

    public static com.google.protobuf.Parser<reqlogin> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface resloginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:reslogin)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int64 playerId = 1;</code>
     */
    long getPlayerId();
  }
  /**
   * Protobuf type {@code reslogin}
   */
  public  static final class reslogin extends
      com.google.protobuf.GeneratedMessageLite<
          reslogin, reslogin.Builder> implements
      // @@protoc_insertion_point(message_implements:reslogin)
      resloginOrBuilder {
    private reslogin() {
    }
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    private void setPlayerId(long value) {
      
      playerId_ = value;
    }
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    private void clearPlayerId() {
      
      playerId_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerId_ != 0L) {
        output.writeInt64(1, playerId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code reslogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin, Builder> implements
        // @@protoc_insertion_point(builder_implements:reslogin)
        com.zyyApp.Netty.ServerTest.Message.protocol.Login.resloginOrBuilder {
      // Construct using com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public long getPlayerId() {
        return instance.getPlayerId();
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public Builder setPlayerId(long value) {
        copyOnWrite();
        instance.setPlayerId(value);
        return this;
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        copyOnWrite();
        instance.clearPlayerId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:reslogin)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin other = (com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin) arg1;
          playerId_ = visitor.visitLong(playerId_ != 0L, playerId_,
              other.playerId_ != 0L, other.playerId_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  playerId_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:reslogin)
    private static final com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new reslogin();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reslogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<reslogin> PARSER;

    public static com.google.protobuf.Parser<reslogin> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface reqQuitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:reqQuit)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code reqQuit}
   */
  public  static final class reqQuit extends
      com.google.protobuf.GeneratedMessageLite<
          reqQuit, reqQuit.Builder> implements
      // @@protoc_insertion_point(message_implements:reqQuit)
      reqQuitOrBuilder {
    private reqQuit() {
    }
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSerializedSize = size;
      return size;
    }

    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code reqQuit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit, Builder> implements
        // @@protoc_insertion_point(builder_implements:reqQuit)
        com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuitOrBuilder {
      // Construct using com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:reqQuit)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit other = (com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit) arg1;
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:reqQuit)
    private static final com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new reqQuit();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.reqQuit getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<reqQuit> PARSER;

    public static com.google.protobuf.Parser<reqQuit> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface resQuitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:resQuit)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int64 playerId = 1;</code>
     */
    long getPlayerId();
  }
  /**
   * Protobuf type {@code resQuit}
   */
  public  static final class resQuit extends
      com.google.protobuf.GeneratedMessageLite<
          resQuit, resQuit.Builder> implements
      // @@protoc_insertion_point(message_implements:resQuit)
      resQuitOrBuilder {
    private resQuit() {
    }
    public static final int PLAYERID_FIELD_NUMBER = 1;
    private long playerId_;
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    public long getPlayerId() {
      return playerId_;
    }
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    private void setPlayerId(long value) {
      
      playerId_ = value;
    }
    /**
     * <code>optional int64 playerId = 1;</code>
     */
    private void clearPlayerId() {
      
      playerId_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (playerId_ != 0L) {
        output.writeInt64(1, playerId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (playerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playerId_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code resQuit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit, Builder> implements
        // @@protoc_insertion_point(builder_implements:resQuit)
        com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuitOrBuilder {
      // Construct using com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public long getPlayerId() {
        return instance.getPlayerId();
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public Builder setPlayerId(long value) {
        copyOnWrite();
        instance.setPlayerId(value);
        return this;
      }
      /**
       * <code>optional int64 playerId = 1;</code>
       */
      public Builder clearPlayerId() {
        copyOnWrite();
        instance.clearPlayerId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:resQuit)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit other = (com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit) arg1;
          playerId_ = visitor.visitLong(playerId_ != 0L, playerId_,
              other.playerId_ != 0L, other.playerId_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  playerId_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:resQuit)
    private static final com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new resQuit();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.zyyApp.Netty.ServerTest.Message.protocol.Login.resQuit getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<resQuit> PARSER;

    public static com.google.protobuf.Parser<resQuit> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
